name: Code Review bot trigger
on:
  pull_request_target:
    types: [opened, reopened]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6
        with:
          sparse-checkout: "python/code-review"

      - name: setup Python deps
        run: pip install requests

      - name: lando-push-to-try
        run: python ./python/code-review/lando.py

        env:
          # Expose the pull request number as it's not available in Github Actions env variables
          GITHUB_PR_NUMBER: ${{ github.event.number }}

          # Lando Auth is provided from Github actions secrets
          LANDO_API_TOKEN: ${{ secrets.LandoAPIToken }}
